version: "3.8"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8888:8888"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
